insert into Member (id, name, email, phone_number) values (0, 'John Smith', 'john.smith@mailinator.com', '2125551212')
insert into Member (id, name, email, phone_number) values (1, 'Anton Defoa', 'anton.defoa@mailinator.com', '1234567892')
insert into Banks (id, title, identifier) values (0, 'ČSOB', 'CSOB')
insert into Categories (id, title) values (0, 'Home')
insert into Categories (id, title) values (1, 'Job')
insert into Categories (id, title) values (2, 'Garden')
insert into Users (id, name, forname) values(0, "Carl", "Hostings")
insert into Users (id, name, forname) values(1, "Peter", "Nash")